hsp = 0;
vsp = 0;
grv = 0.3;
kecepatan = 2;
tangga = false;
flip_status = 1; // 0: menghadap ke kanan, 1: menghadap ke kiri
animation_speed = 0.1; // Kecepatan animasi 
damage_pemain = 20;
hp = 250;
stamina_max = 100; // Jumlah maksimum stamina pemain
stamina = stamina_max; // Inisialisasi stamina awal
stamina_depletion_rate = 1; // Tingkat pengurangan stamina saat menyerang
stamina_regeneration_rate = 0.5; // Tingkat regenerasi stamina saat tidak menyerang
attack_cooldown = 60; // Cooldown serangan (dalam frame)
attack_timer = 0; // Timer serangan
previous_room = room;