hsp = 0;
vsp = 0;
grv = 0.1;
kecepatan = 4;
tangga = false;
flip_status = 1; // 0: menghadap ke kanan, 1: menghadap ke kiri
animation_speed = 0.1; // Kecepatan animasi (ubah sesuai kebutuhan)
damage_pemain = 20;
hp = 100;
stamina_max = 100; // Jumlah maksimum stamina pemain
stamina = stamina_max; // Inisialisasi stamina awal
stamina_depletion_rate = 1; // Tingkat pengurangan stamina saat menyerang
stamina_regeneration_rate = 0.5; // Tingkat regenerasi stamina saat tidak menyerang
attack_cooldown = 60; // Cooldown serangan (dalam frame)
attack_timer = 0; // Timer serangan
previous_room = room;
inventory_item[0] = 0; // Kuantitas item 1 (indeks 0) diatur ke 0
inventory_item[1] = 0; // Kuantitas item 2 (indeks 1) diatur ke 0
inventory_item[2] = 0; // Kuantitas item 3 (indeks 1) diatur ke 0
inventory_item[3] = 0; // Kuantitas item 4 (indeks 1) diatur ke 0